"""PDF export functionality for movie details."""

import io
from reportlab.lib.pagesizes import letter, A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, PageBreak, Table, TableStyle, Image
from reportlab.lib import colors
from typing import Dict, Optional
from io import BytesIO


def create_movie_pdf(movie: Dict) -> bytes:
    """Create a PDF document with movie details.
    
    Args:
        movie: Movie details dictionary
        
    Returns:
        PDF file as bytes
    """
    buffer = BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=letter, topMargin=0.5*inch, bottomMargin=0.5*inch)
    
    # Styles
    styles = getSampleStyleSheet()
    title_style = ParagraphStyle(
        'CustomTitle',
        parent=styles['Heading1'],
        fontSize=24,
        textColor=colors.HexColor('#1F77B4'),
        spaceAfter=12,
        alignment=1  # Center
    )
    
    heading_style = ParagraphStyle(
        'CustomHeading',
        parent=styles['Heading2'],
        fontSize=14,
        textColor=colors.HexColor('#2E86AB'),
        spaceAfter=6,
        spaceBefore=6
    )
    
    # Build content
    story = []
    
    # Title
    story.append(Paragraph(movie.get('title', 'Unknown'), title_style))
    story.append(Spacer(1, 0.2*inch))
    
    # Basic Info
    info_data = [
        ['Release Date', movie.get('release_date', 'N/A')],
        ['Runtime', f"{movie.get('runtime', 'N/A')} minutes"],
        ['Rating', f"{movie.get('vote_average', 'N/A')} / 10"],
        ['Status', movie.get('status', 'N/A')],
    ]
    info_table = Table(info_data, colWidths=[2*inch, 4*inch])
    info_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (0, -1), colors.HexColor('#E8F2F5')),
        ('TEXTCOLOR', (0, 0), (-1, -1), colors.black),
        ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
        ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, -1), 10),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
        ('GRID', (0, 0), (-1, -1), 1, colors.grey),
    ]))
    story.append(info_table)
    story.append(Spacer(1, 0.2*inch))
    
    # Overview
    story.append(Paragraph("Overview", heading_style))
    overview = movie.get('overview', 'No overview available')
    story.append(Paragraph(overview, styles['BodyText']))
    story.append(Spacer(1, 0.2*inch))
    
    # Genres
    genres = movie.get('genres', [])
    if genres:
        genre_names = ', '.join([g['name'] for g in genres])
        story.append(Paragraph("Genres", heading_style))
        story.append(Paragraph(genre_names, styles['BodyText']))
        story.append(Spacer(1, 0.2*inch))
    
    # Financial Info
    budget = movie.get('budget')
    revenue = movie.get('revenue')
    if budget or revenue:
        story.append(Paragraph("Financial Information", heading_style))
        fin_data = []
        if budget and budget > 0:
            fin_data.append(['Budget', f"${budget:,.0f}"])
        if revenue and revenue > 0:
            fin_data.append(['Revenue', f"${revenue:,.0f}"])
        if fin_data:
            fin_table = Table(fin_data, colWidths=[2*inch, 4*inch])
            fin_table.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (0, -1), colors.HexColor('#E8F2F5')),
                ('TEXTCOLOR', (0, 0), (-1, -1), colors.black),
                ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
                ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
                ('FONTSIZE', (0, 0), (-1, -1), 10),
                ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
                ('GRID', (0, 0), (-1, -1), 1, colors.grey),
            ]))
            story.append(fin_table)
        story.append(Spacer(1, 0.2*inch))
    
    # Additional info
    story.append(Paragraph("Additional Information", heading_style))
    add_data = [
        ['Popularity', str(movie.get('popularity', 'N/A'))],
        ['Vote Count', str(movie.get('vote_count', 'N/A'))],
        ['Original Language', movie.get('original_language', 'N/A').upper()],
    ]
    add_table = Table(add_data, colWidths=[2*inch, 4*inch])
    add_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (0, -1), colors.HexColor('#E8F2F5')),
        ('TEXTCOLOR', (0, 0), (-1, -1), colors.black),
        ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
        ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, -1), 10),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
        ('GRID', (0, 0), (-1, -1), 1, colors.grey),
    ]))
    story.append(add_table)
    
    # Footer
    story.append(Spacer(1, 0.3*inch))
    story.append(Paragraph("Generated by Movie Detail App | Powered by TMDB", styles['Normal']))
    
    # Build PDF
    doc.build(story)
    buffer.seek(0)
    return buffer.getvalue()
